name: CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Ehsan
      uses: appleboy/ssh-action@master
      with:
        host: 185.110.189.5
        port: 22
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: "cd /rdl/ && git pull origin master && pm2 restart 9"
    - run: laravel.sh
     
